# Generated by Django 4.2.7 on 2025-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('rider', 'Rider'), ('dispatcher', 'Dispatcher')], default='rider', help_text='User role (admin, driver, rider, dispatcher)', max_length=20)),
                ('first_name', models.CharField(help_text="User's first name", max_length=150)),
                ('last_name', models.CharField(help_text="User's last name", max_length=150)),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text="User's phone number", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
    ]
