# Generated by Django 4.2.7 on 2025-07-15 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id_ride', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('en-route', 'En Route'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='en-route', help_text="Ride status (e.g., 'en-route', 'pickup', 'dropoff')", max_length=20)),
                ('pickup_latitude', models.FloatField(help_text='Latitude of pickup location')),
                ('pickup_longitude', models.FloatField(help_text='Longitude of pickup location')),
                ('dropoff_latitude', models.FloatField(help_text='Latitude of dropoff location')),
                ('dropoff_longitude', models.FloatField(help_text='Longitude of dropoff location')),
                ('pickup_time', models.DateTimeField(help_text='Pickup time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_driver', models.ForeignKey(help_text='Foreign key referencing User(id_user) - the driver', on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
                ('id_rider', models.ForeignKey(help_text='Foreign key referencing User(id_user) - the rider', on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'db_table': 'ride',
                'ordering': ['-pickup_time'],
                'indexes': [models.Index(fields=['status'], name='ride_status_4ce3bb_idx'), models.Index(fields=['pickup_time'], name='ride_pickup__112ef2_idx'), models.Index(fields=['id_rider'], name='ride_id_ride_030ef8_idx'), models.Index(fields=['id_driver'], name='ride_id_driv_1d5b88_idx'), models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='ride_pickup__22d4cb_idx')],
            },
        ),
    ]
