# Generated by Django 4.2.7 on 2025-07-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id_ride_event', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Description of the ride event', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the event occurred')),
                ('id_ride', models.ForeignKey(help_text='Foreign key referencing Ride(id_ride)', on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Ride Event',
                'verbose_name_plural': 'Ride Events',
                'db_table': 'ride_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_ride'], name='ride_event_id_ride_4d8be4_idx'), models.Index(fields=['created_at'], name='ride_event_created_fda889_idx'), models.Index(fields=['id_ride', 'created_at'], name='ride_event_id_ride_078fd3_idx')],
            },
        ),
    ]
